spring.application.name=springEcommerce

spring.datasource.url=jdbc:mysql://root:lTluTBGfOtCXKDPcIQCCfaobDVmRcBIU@acela.proxy.rlwy.net:36080/railway?useSSL=true&requireSSL=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=lTluTBGfOtCXKDPcIQCCfaobDVmRcBIU
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


